apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: public.ecr.aws/d0x9x5l1/jenkinsecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
